# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c63f8707faf672039f3342deb64688967a6c899bed4aaf3d921483726983206ab426c28fb852b04a79da9069e48fa03a99b69202d95d3beafffa4aaaa5b42cc9

test:
  secret_key_base: c4e9c0c6309b0609bbb232e9b998a6470d4ad770688c7bfa5278f00cc38df8c67643047f58661eabbe4a77b25303e66b4a84a63cb73eeb57b4e480e2818fcfc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
